### PR TITLE
Implemented close method for CvCapture

### PR DESCRIPTION
**Pull request by skateman**
Sometimes it is useful to release a resource BEFORE the garbage collection starts

### CODE REVIEW

**Comment by ser1zw** [comment]
Thank you!
I'll merge the changes.

**Comment by skateman** [comment]
Thanks @ser1zw, when will this pushed to a new release?

**Comment by ser1zw** [comment]
I'll do it this weekend.

**Comment by skateman** [comment]
great :) thx

**Comment by ser1zw** [comment]
Released v0.0.16 https://rubygems.org/gems/ruby-opencv/versions/0.0.16

**Pull request merged**
